# encoding: utf-8
# -----------------------------------------------------------------------------
# Project   : Fake
# -----------------------------------------------------------------------------
# Thin export surface. Implementation lives in data.py and anon.py.
# -----------------------------------------------------------------------------

from .anon import anonymize, fuzz, deanonymize, redact  # noqa: F401

from .data import (
    VERSION,
    DATA,
    seed,
    name,
    firstName,
    lastName,
    email,
    emails,
    company,
    user,
    phone,
    zip,
    address,
    city,
    country,
    day,
    month,
    seconds,
    hour,
    now,
    number,
    date,
    time,
    word,
    words,
    text,
    title,
    paragraph,
    topic,
    choice,
    pick,
    combination,
    subset,
    password,
    apiKey,
)

__all__ = [
    "VERSION",
    "DATA",
    "anonymize",
    "fuzz",
    "deanonymize",
    "redact",
    "seed",
    "name",
    "firstName",
    "lastName",
    "email",
    "emails",
    "company",
    "user",
    "phone",
    "zip",
    "address",
    "city",
    "country",
    "day",
    "month",
    "seconds",
    "hour",
    "now",
    "number",
    "date",
    "time",
    "word",
    "words",
    "text",
    "title",
    "paragraph",
    "topic",
    "choice",
    "pick",
    "combination",
    "subset",
    "password",
    "apiKey",
]
